#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use RodrigoPedra\LaravelRecordProcessor\Examples\ExamplesCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add( new ExamplesCommand );

$application->run();
